# -*- coding: utf-8 -*-
"""
Stage 3 — deterministic format check. Produces fix objects (valid JSON, correct
field names — generated by this script, never by a model).

    python 30_check_format.py <workdir>

Reads <workdir>/structure.json, runs per-paragraph checks + page setup +
continuity + document-level hints, and writes <workdir>/fixes.json and
<workdir>/report.json. The whole document is processed in this single Python
pass — no document text is ever loaded into the model's context — so it handles
documents of any size without needing to be split up.

Prints a COMPACT summary JSON to stdout.
"""
import json
import os
import sys

HERE = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(HERE, "lib"))
import checks


def main():
    if len(sys.argv) < 2:
        print(json.dumps({"status": "error",
                          "error": "usage: 30_check_format.py <workdir>"}))
        sys.exit(1)
    workdir = sys.argv[1]
    spec = checks.load_default_spec()

    with open(os.path.join(workdir, "structure.json"), encoding="utf-8") as f:
        structure = json.load(f)
    records = structure["records"]

    fixes = []
    ps = checks.check_page_setup(structure.get("page_setup"), spec)
    if ps:
        fixes.append(ps)
    for rec in records:
        fx = checks.check_paragraph(rec, spec)
        if fx:
            fixes.append(fx)
    fixes.extend(checks.continuity(records, spec))
    fixes.extend(checks.doc_hints(structure, spec))

    _write_fixes(workdir, fixes)


def _write_fixes(workdir, fixes):
    with open(os.path.join(workdir, "fixes.json"), "w", encoding="utf-8") as f:
        json.dump(fixes, f, ensure_ascii=False, indent=1)
    # report
    by_op, by_rule = {}, {}
    for fx in fixes:
        by_op[fx["op"]] = by_op.get(fx["op"], 0) + 1
        by_rule[fx["rule_id"]] = by_rule.get(fx["rule_id"], 0) + 1
    report = {"status": "ok", "n_fixes": len(fixes),
              "by_op": by_op, "by_rule": by_rule}
    with open(os.path.join(workdir, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
