# -*- coding: utf-8 -*-
"""
Stage 3 — deterministic format check. Produces fix objects (valid JSON, correct
field names — generated by this script, never by a model).

Two modes:
  FULL (default):
      python 30_check_format.py <workdir>
      Reads <workdir>/structure.json, runs per-paragraph checks + page setup +
      continuity + document-level hints, writes <workdir>/fixes.json and
      <workdir>/report.json. Use this when NOT delegating to sub-agents.

  SHARD:
      python 30_check_format.py <workdir> --shard <shards/shard_00X.json>
      Runs ONLY per-paragraph format checks for that shard, writes
      <workdir>/fixes_parts/<shardname>. Continuity & doc hints are handled by
      31_check_global.py. Use this when delegating shards to sub-agents so each
      sub-agent processes a slice and returns only compact counts.

Prints a COMPACT summary JSON to stdout in both modes.
"""
import json
import os
import sys

HERE = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(HERE, "lib"))
import checks


def main():
    if len(sys.argv) < 2:
        print(json.dumps({"status": "error",
                          "error": "usage: 30_check_format.py <workdir> [--shard <file>]"}))
        sys.exit(1)
    workdir = sys.argv[1]
    spec = checks.load_default_spec()

    if "--shard" in sys.argv:
        shard_file = sys.argv[sys.argv.index("--shard") + 1]
        with open(shard_file, encoding="utf-8") as f:
            shard = json.load(f)
        fixes = []
        for rec in shard["records"]:
            fx = checks.check_paragraph(rec, spec)
            if fx:
                fixes.append(fx)
        parts = os.path.join(workdir, "fixes_parts")
        os.makedirs(parts, exist_ok=True)
        name = os.path.basename(shard_file)
        with open(os.path.join(parts, name), "w", encoding="utf-8") as f:
            json.dump(fixes, f, ensure_ascii=False)
        print(json.dumps({"status": "ok", "mode": "shard", "shard": name,
                          "range": shard.get("range"), "n_fixes": len(fixes)},
                         ensure_ascii=False))
        return

    # FULL mode
    with open(os.path.join(workdir, "structure.json"), encoding="utf-8") as f:
        structure = json.load(f)
    records = structure["records"]

    fixes = []
    ps = checks.check_page_setup(structure.get("page_setup"), spec)
    if ps:
        fixes.append(ps)
    for rec in records:
        fx = checks.check_paragraph(rec, spec)
        if fx:
            fixes.append(fx)
    fixes.extend(checks.continuity(records, spec))
    fixes.extend(checks.doc_hints(structure, spec))

    _write_fixes(workdir, fixes)


def _write_fixes(workdir, fixes):
    with open(os.path.join(workdir, "fixes.json"), "w", encoding="utf-8") as f:
        json.dump(fixes, f, ensure_ascii=False, indent=1)
    # report
    by_op, by_rule = {}, {}
    for fx in fixes:
        by_op[fx["op"]] = by_op.get(fx["op"], 0) + 1
        by_rule[fx["rule_id"]] = by_rule.get(fx["rule_id"], 0) + 1
    report = {"status": "ok", "mode": "full", "n_fixes": len(fixes),
              "by_op": by_op, "by_rule": by_rule}
    with open(os.path.join(workdir, "report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
