# -*- coding: utf-8 -*-
"""Stage 5 — human-readable change summary (Markdown).

Usage:
    python 55_summary.py <workdir>

Reads the STRUCTURED artifacts produced upstream — never re-parses comment text:
    <workdir>/fixes.json        (the deterministic fix list from checks)
    <workdir>/apply_report.json (per-op applied counts + problems, from 40)
    <workdir>/meta.json         (original file name, for the header)
    <workdir>/structure.json    (OPTIONAL; only to show a text snippet per row)

Writes <workdir>/summary.md — one row per fix with its category, a text snippet,
the violated spec clause (rule_text, already generated by checks.py), and the
application status (已修正 / 提示，需人工核实 / 应用失败，需人工核实). Because it
reads fixes.json (not the .docx comments), the table never goes empty just
because a comment's wording changed.

Delivered alongside formatted.docx so the user can review every change at a
glance instead of scrolling hundreds of in-document comments.
"""
import json
import os
import sys
from datetime import datetime

# op -> coarse category label
OP_CATEGORY = {
    "format": "格式（字体/字号/行距/缩进）",
    "renumber_heading": "标题序号",
    "renumber_caption": "图表编号",
    "section": "页面边距",
}
# hint rule_id -> category label (finer than the bare "提示")
HINT_CATEGORY = {
    "cover.fields": "封面缺少必要信息",
    "cover.placeholder": "封面标题占位符未替换",
    "cover.green": "封面背景颜色",
    "caption.content": "图表缺少内容说明",
    "heading.unconfirmed": "疑似标题（未确认）",
}


def _hint_category(rule_id):
    if rule_id in HINT_CATEGORY:
        return HINT_CATEGORY[rule_id]
    if rule_id.startswith("caption.") and rule_id.endswith(".unconfirmed"):
        return "疑似图表标题（未确认）"
    if rule_id.startswith("caption.") and rule_id.endswith(".missing_number"):
        return "图表漏编号（未确认）"
    return "提示项"


def _category(fix):
    op = fix.get("op")
    if op == "hint":
        return _hint_category(fix.get("rule_id") or "")
    return OP_CATEGORY.get(op, op or "其他")


def _load_texts(workdir):
    """{para_index: text} from structure.json, if present. Kept out of the model
    context — this is a script reading a file on disk, truncated per row below."""
    path = os.path.join(workdir, "structure.json")
    if not os.path.exists(path):
        return {}
    try:
        data = json.load(open(path, encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    texts = {}
    for r in data.get("records", []):
        i = r.get("i")
        if i is not None:
            texts[i] = r.get("text") or ""
    return texts


def _snippet(text, limit=30):
    t = (text or "").strip().replace("\n", " ")
    if len(t) > limit:
        t = t[:limit] + "…"
    # escape the Markdown table cell separator
    return t.replace("|", "\\|") or "—"


def _md_escape(s):
    return (s or "").replace("\n", " ").replace("|", "\\|")


def main():
    if len(sys.argv) < 2:
        print(json.dumps({"status": "error",
                          "error": "usage: 55_summary.py <workdir>"}))
        sys.exit(1)
    workdir = sys.argv[1]

    fixes_path = os.path.join(workdir, "fixes.json")
    if not os.path.exists(fixes_path):
        print(json.dumps({"status": "error",
                          "error": "fixes.json not found; run 30/35 first"},
                         ensure_ascii=False))
        sys.exit(1)
    fixes = json.load(open(fixes_path, encoding="utf-8"))

    apply_report = {}
    ap = os.path.join(workdir, "apply_report.json")
    if os.path.exists(ap):
        try:
            apply_report = json.load(open(ap, encoding="utf-8"))
        except (OSError, ValueError):
            apply_report = {}
    # (para_index, op) pairs that failed to apply
    problem_keys = {(p.get("para_index"), p.get("op"))
                    for p in apply_report.get("problems", [])}

    meta = {}
    mp = os.path.join(workdir, "meta.json")
    if os.path.exists(mp):
        try:
            meta = json.load(open(mp, encoding="utf-8"))
        except (OSError, ValueError):
            meta = {}

    texts = _load_texts(workdir)

    rows = []
    cat_counts = {}
    n_fixed = n_hint = n_failed = 0
    for fix in fixes:
        op = fix.get("op")
        idx = fix.get("para_index")
        cat = _category(fix)
        cat_counts[cat] = cat_counts.get(cat, 0) + 1

        if op == "hint":
            status = "提示，需人工核实"
            n_hint += 1
        elif (idx, op) in problem_keys:
            status = "应用失败，需人工核实"
            n_failed += 1
        else:
            status = "已修正"
            n_fixed += 1

        loc = "第%s段" % idx if idx is not None else "全文"
        snippet = _snippet(texts.get(idx)) if idx is not None else "（页面级）"
        rows.append((idx if idx is not None else -1, op, loc, cat, snippet,
                     _md_escape(fix.get("rule_text") or ""), status))

    # order: by paragraph index, section (idx=-1) rows first
    rows.sort(key=lambda r: (r[0],))

    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    stem = meta.get("original_stem", "")
    ext = meta.get("original_ext", "")
    orig_name = ("%s.%s" % (stem, ext)) if stem else "（未知）"

    lines = []
    lines.append("# 格式审查修改汇总")
    lines.append("")
    lines.append("- 原文件：%s" % orig_name)
    lines.append("- 生成时间：%s" % ts)
    lines.append("- 修改/提示总数：%d（已修正 %d，提示待人工 %d，应用失败 %d）"
                 % (len(fixes), n_fixed, n_hint, n_failed))
    lines.append("")
    lines.append("> 已修正项已在 `formatted.docx` 中改好并逐处附 XAgent 批注；"
                 "「提示」「应用失败」项脚本未擅自改动，需人工核实。")
    lines.append("")

    lines.append("## 按类别统计")
    lines.append("")
    lines.append("| 类别 | 数量 |")
    lines.append("| --- | ---: |")
    for cat, n in sorted(cat_counts.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append("| %s | %d |" % (cat, n))
    lines.append("")

    lines.append("## 明细")
    lines.append("")
    lines.append("| 位置 | 类别 | 内容摘要 | 规范依据 | 状态 |")
    lines.append("| --- | --- | --- | --- | --- |")
    for _idx, _op, loc, cat, snippet, rule_text, status in rows:
        lines.append("| %s | %s | %s | %s | %s |"
                     % (loc, cat, snippet, rule_text, status))
    lines.append("")

    out_path = os.path.join(workdir, "summary.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    result = {"status": "ok", "summary_md": out_path,
              "total": len(fixes), "fixed": n_fixed,
              "hints": n_hint, "failed": n_failed}
    json.dump(result, open(os.path.join(workdir, "summary_report.json"), "w",
                           encoding="utf-8"), ensure_ascii=False, indent=1)
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
